### ISSUE TITLE
The hyparameters settings of FashionMNIST and MNIST experiments

### ISSUE THREAD

**Issue by LittlelittleZ** [k2cu8/pyOMT#1]
Hello, 
I try to implement the FashionMNIST and MNIST result with the OT map's learning rate and the E(h) threshold same as the settings of  demo2, but I failed, these two experiments did not converge, the E(h) (g norm) value oscillates between 0.03 and 1 even though the noise number had  increased to 40960000 and without a downward trend.
I wonder if the learning rate is important to OT map? if the E(h) value has a big difference in different datasets? I've tried for a long time, I hope I can get some advice from you, thank you very much!

**Comment by k2cu8** [comment]
Hi there, the learning rate is important here. Since each step the gradient is estimated by monte-carlo method, a proper step size is needed for convergence. I would suggest starting with small learning rates and see if it converges.

**Comment by LittlelittleZ** [comment]
Hi, I've tried to adjust the lr and solved the problem, thank you so much!
